database:
    host: 192.168.137.1
    port: 3306
    name: videoserver

server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://${database.host}:${database.port}/${database.name}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 1000
        initialSize: 10
        maxWait: 60000
        minIdle: 5
        test-on-borrow: true 
        test-on-return: true
        validation-query: SELECT 1
        
    http:
        multipart:
            max-file-size: 5120Mb
            max-request-size: 5120Mb

mybatis: 
    mapperLocations: classpath:/mapper/*.xml
    typeAliasesPackage: com.video.scanning.domain
    
#monitor           
management:
    port: 8097
    security:
        enabled: false
            
logging:
    level:
        root: INFO
        com:
            video:
                scanning:
                   dao: debug
    file: logs/video-scanning.log
