#设定文件存储路径
videoscanning:
  upload:
    dir: F://uploadfile
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880

spring:
    profiles: dev


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql